---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: confluent-cloud
  links:
    - url: https://confluent.cloud
      title: Confluent Cloud Console
      icon: dashboard
spec:
  owner: guests
