---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ${GITHUB_USER_NAME}
  annotations:
    # This can vary depending on your resolver config, but for GitHub you often need:
    github.com/login: ${GITHUB_USER_NAME}
spec:
  profile:
    displayName: ${GITHUB_USER_DISPLAY_NAME}
    email: ${GITHUB_USER_EMAIL}
  memberOf: [guests]

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
